name: Buildroot

on:
  push:

jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      tags: |
        waterlemons2k/buildroot
        waterlemons2k/buildroot:2022.11
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
